const user=session.get();
if(!user||user.role!=='ADMIN') location.href='login.html';
document.getElementById('adminName').textContent=user?.name||'Administrator';
document.getElementById('logout').onclick=e=>{e.preventDefault();session.clear();location.href='login.html'};
const content=document.getElementById('content'), title=document.getElementById('viewTitle'), modalBg=document.getElementById('modalBg'), modal=document.getElementById('modal');
let currentView='dashboard';
const money=v=>`Rs. ${Number(v||0).toLocaleString('en-LK',{minimumFractionDigits:2,maximumFractionDigits:2})}`;

const ADMIN_PRODUCT_IMAGES={
 'premium rice pack':'premium-rice.jpg','organic oats':'organic-oats.jpg','pasta fusilli':'pasta-fusilli.jpg','coconut milk pack':'coconut-milk.jpg',
 'wireless headphones':'wireless-headphones.jpg','smart fitness band':'fitness-band.jpg','portable bluetooth speaker':'bluetooth-speaker.jpg','usb-c fast charger':'usb-charger.jpg',
 'ceylon tea premium':'ceylon-tea.jpg','arabica coffee 250g':'arabica-coffee.jpg','tropical mango juice':'mango-juice.jpg','mineral water 6 pack':'mineral-water.jpg',
 'eco laundry liquid':'laundry-liquid.jpg','dish wash lemon':'dish-wash.jpg','multipurpose cleaner':'cleaner.jpg','soft tissue 6 pack':'tissue.jpg',
 'herbal shampoo':'shampoo.jpg','aloe body wash':'body-wash.jpg','roasted cashew mix':'cashew-mix.jpg','premium notebook set':'notebook-set.jpg','fresh apple pack':'fresh-apple.jpg','banana bunch':'banana-bunch.jpg','ballpoint pen set':'ballpoint-pens.jpg'
};
const ADMIN_CATEGORY_IMAGES={'groceries':'category-groceries.jpg','electronics':'category-electronics.jpg','beverages':'category-beverages.jpg','household':'category-household.jpg','personal care':'category-personal-care.jpg','snacks':'category-snacks.jpg','fresh produce':'category-fresh-produce.jpg','stationery':'category-stationery.jpg'};
function adminProductImage(p){const f=ADMIN_PRODUCT_IMAGES[String(p?.name||'').toLowerCase()]||ADMIN_CATEGORY_IMAGES[String(p?.category?.name||'').toLowerCase()]||'category-groceries.jpg';return `assets/products/${f}`}
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function notify(msg,error=false){const t=document.getElementById('toast');t.textContent=msg;t.style.background=error?'#b91c1c':'#166534';t.style.display='block';clearTimeout(window.__at);window.__at=setTimeout(()=>t.style.display='none',2600)}
function closeModal(){modalBg.style.display='none';modal.innerHTML=''}
modalBg.onclick=e=>{if(e.target===modalBg)closeModal()};
function openModal(header,body,onSubmit){modal.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:1.2rem"><h3>${header}</h3><button class="btn btn-light btn-sm" id="modalClose">✕</button></div><form id="modalForm">${body}<div class="modal-actions"><button type="button" class="btn btn-light" id="cancelModal">Cancel</button><button class="btn btn-primary">Save</button></div></form>`;modalBg.style.display='flex';document.getElementById('modalClose').onclick=closeModal;document.getElementById('cancelModal').onclick=closeModal;document.getElementById('modalForm').onsubmit=async e=>{e.preventDefault();try{await onSubmit(new FormData(e.target));closeModal();notify('Saved successfully.');views[currentView]()}catch(err){notify(err.message,true)}}}
function badge(status=''){const s=status.toLowerCase();let c='muted';if(['active','in stock','completed','delivered'].includes(s))c='success';else if(['low stock','pending','preparing'].includes(s))c='warning';else if(['out of stock','cancelled','inactive'].includes(s))c='danger';else if(['confirmed','shipped','admin'].includes(s))c='info';return `<span class="badge ${c}">${esc(status)}</span>`}
function pageHead(name,desc,button=''){return `<div class="view-head"><div><h1>${name}</h1><p>${desc}</p></div>${button}</div>`}
function table(headers,rows){return `<div class="card"><div class="table-wrap"><table class="table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${headers.length}"><div class="empty">No records found.</div></td></tr>`}</tbody></table></div></div>`}
async function confirmDelete(fn){if(!confirm('Delete this record?'))return;try{await fn();notify('Deleted successfully.');views[currentView]()}catch(e){notify(e.message,true)}}
function options(list,value,label='name'){return list.map(x=>`<option value="${x.id}">${esc(x[label])}</option>`).join('')}
const views={
 dashboard:async()=>{title.textContent='Dashboard';content.innerHTML=pageHead('Administrator Dashboard','Monitor and manage the Online Market Store.')+'<div class="empty">Loading...</div>';try{const s=await api.adminSummary();const cards=[['Categories',s.categories,'fa-layer-group','categories'],['Companies',s.companies,'fa-building','companies'],['Products',s.products,'fa-box-open','products'],['Inventory',s.inventory,'fa-boxes-stacked','inventory'],['Active Promotions',s.activePromotions,'fa-tags','promotions'],['Orders',s.orders,'fa-receipt','orders'],['Deliveries',s.deliveries,'fa-truck','deliveries'],['Users',s.users,'fa-users','users']];content.innerHTML=pageHead('Administrator Dashboard','A single operational view across all six major project functions.')+`<div class="stats">${cards.map(c=>`<div class="stat" onclick="switchView('${c[3]}')" style="cursor:pointer"><div class="stat-icon"><i class="fas ${c[2]}"></i></div><div><strong>${c[1]}</strong><span>${c[0]}</span></div></div>`).join('')}</div><div class="card" style="padding:1.6rem"><h3>Module quick actions</h3><p style="color:#66756e;margin:.4rem 0 1rem">Jump straight into the functions most useful during the final project demonstration.</p><div class="quick-grid"><button class="quick-action" onclick="switchView('products')"><i class="fas fa-box-open"></i><strong>Product & Category</strong><span>Catalogue management</span></button><button class="quick-action" onclick="switchView('inventory')"><i class="fas fa-boxes-stacked"></i><strong>Inventory</strong><span>Stock quantities & status</span></button><button class="quick-action" onclick="switchView('promotions')"><i class="fas fa-tags"></i><strong>Promotions</strong><span>Strategy Pattern discounts</span></button><button class="quick-action" onclick="switchView('orders')"><i class="fas fa-receipt"></i><strong>Orders & Delivery</strong><span>Processing and fulfilment</span></button></div><div class="module-note"><i class="fas fa-link"></i> All modules use the same SQL Server database and REST API</div></div>`}catch(e){content.innerHTML=`<div class="empty">${esc(e.message)}</div>`}},
 categories:async()=>{title.textContent='Categories';const data=await api.categories();content.innerHTML=pageHead('Category Management','Create and maintain product categories.','<button class="btn btn-primary" id="add"><i class="fas fa-plus"></i> Add Category</button>')+table(['ID','Category','Actions'],data.map(x=>`<tr data-search="${esc(x.name).toLowerCase()}"><td>#${x.id}</td><td><strong>${esc(x.name)}</strong></td><td class="actions"><button class="btn btn-light btn-sm" onclick='editCategory(${JSON.stringify(x)})'>Edit</button><button class="btn btn-danger btn-sm" onclick="confirmDelete(()=>api.deleteCategory(${x.id}))">Delete</button></td></tr>`).join(''));document.getElementById('add').onclick=()=>editCategory(null)},
 companies:async()=>{title.textContent='Companies';const data=await api.companies();content.innerHTML=pageHead('Company Management','Manage suppliers and companies linked to products.','<button class="btn btn-primary" id="add"><i class="fas fa-plus"></i> Add Company</button>')+table(['ID','Company','Email','Phone','Address','Actions'],data.map(x=>`<tr data-search="${esc((x.name+' '+(x.email||'')).toLowerCase())}"><td>#${x.id}</td><td><strong>${esc(x.name)}</strong></td><td>${esc(x.email||'—')}</td><td>${esc(x.phone||'—')}</td><td>${esc(x.address||'—')}</td><td class="actions"><button class="btn btn-light btn-sm" onclick='editCompany(${JSON.stringify(x)})'>Edit</button><button class="btn btn-danger btn-sm" onclick="confirmDelete(()=>api.deleteCompany(${x.id}))">Delete</button></td></tr>`).join(''));document.getElementById('add').onclick=()=>editCompany(null)},
 products:async()=>{title.textContent='Products';const data=await api.products();content.innerHTML=pageHead('Product Management','Products connect categories and companies and feed inventory, promotions and orders.','<button class="btn btn-primary" id="add"><i class="fas fa-plus"></i> Add Product</button>')+table(['ID','Product','Category','Company','Price','Actions'],data.map(x=>`<tr data-search="${esc((x.name+' '+x.category.name+' '+x.company.name).toLowerCase())}"><td>#${x.id}</td><td><div class="admin-product-cell"><img class="admin-product-thumb" src="${adminProductImage(x)}" alt=""><div><strong>${esc(x.name)}</strong><div style="color:#66756e;font-size:.78rem">${esc(x.description||'')}</div></div></div></td><td>${esc(x.category.name)}</td><td>${esc(x.company.name)}</td><td><strong>${money(x.price)}</strong></td><td class="actions"><button class="btn btn-light btn-sm" onclick='editProduct(${JSON.stringify(x)})'>Edit</button><button class="btn btn-danger btn-sm" onclick="confirmDelete(()=>api.deleteProduct(${x.id}))">Delete</button></td></tr>`).join(''));document.getElementById('add').onclick=()=>editProduct(null)},
 inventory:async()=>{title.textContent='Inventory';const [data,products]=await Promise.all([api.inventory(),api.products()]);content.innerHTML=pageHead('Inventory Management','Stock status is calculated automatically from quantity.','<button class="btn btn-primary" id="add"><i class="fas fa-plus"></i> Add Inventory</button>')+table(['ID','Product','Quantity','Status','Actions'],data.map(x=>`<tr data-search="${esc(x.product.name.toLowerCase())}"><td>#${x.id}</td><td><strong>${esc(x.product.name)}</strong></td><td>${x.quantity}</td><td>${badge(x.status)}</td><td class="actions"><button class="btn btn-light btn-sm" onclick='editInventory(${JSON.stringify(x)})'>Edit</button><button class="btn btn-danger btn-sm" onclick="confirmDelete(()=>api.deleteInventory(${x.id}))">Delete</button></td></tr>`).join(''));document.getElementById('add').onclick=()=>editInventory(null,products)},
 promotions:async()=>{title.textContent='Promotions';const data=await api.promotions();content.innerHTML=pageHead('Promotion & Discount Management','Create percentage or fixed-amount discounts using the Strategy Pattern.','<button class="btn btn-primary" id="add"><i class="fas fa-plus"></i> Add Promotion</button>')+table(['ID','Promotion','Product','Price','Discount','Strategy','Dates','Status','Actions'],data.map(x=>{const price=Number(x.product.price);const value=Number(x.discountValue??x.discountPercentage??0);const discounted=x.discountType==='FIXED'?Math.max(0,price-value):price*(1-value/100);const strategy=x.discountType==='FIXED'?'FixedAmountDiscountStrategy':'PercentageDiscountStrategy';return `<tr data-search="${esc((x.name+' '+x.product.name+' '+strategy).toLowerCase())}"><td>#${x.id}</td><td><strong>${esc(x.name)}</strong></td><td>${esc(x.product.name)}</td><td><span class="price-old">${money(price)}</span><span class="price-new">${money(discounted)}</span></td><td><span class="badge warning">${esc(x.discountLabel||'')}</span></td><td><span class="strategy-chip"><i class="fas fa-diagram-project"></i>${strategy}</span></td><td>${x.startDate}<br><small>${x.endDate}</small></td><td>${badge(x.status)}</td><td class="actions"><button class="btn btn-light btn-sm" onclick='editPromotion(${JSON.stringify(x)})'>Edit</button><button class="btn btn-danger btn-sm" onclick="confirmDelete(()=>api.deletePromotion(${x.id}))">Delete</button></td></tr>`}).join(''));document.getElementById('add').onclick=()=>editPromotion(null)},
 orders:async()=>{title.textContent='Orders';const data=await api.orders();content.innerHTML=pageHead('Order Management','Review orders, inspect items and update order status.')+table(['Order','Customer','Date','Total','Status','Actions'],data.map(x=>`<tr data-search="${esc((x.customerName+' '+x.status).toLowerCase())}"><td>#${x.id}</td><td><strong>${esc(x.customerName)}</strong></td><td>${new Date(x.orderDate).toLocaleString()}</td><td><strong>${money(x.totalAmount)}</strong></td><td>${badge(x.status)}</td><td class="actions"><button class="btn btn-light btn-sm" onclick="viewOrder(${x.id})">View</button><button class="btn btn-light btn-sm" onclick='editOrderStatus(${JSON.stringify(x)})'>Status</button><button class="btn btn-danger btn-sm" onclick="confirmDelete(()=>api.deleteOrder(${x.id}))">Delete</button></td></tr>`).join(''))},
 deliveries:async()=>{title.textContent='Deliveries';const [data,orders]=await Promise.all([api.deliveries(),api.orders()]);content.innerHTML=pageHead('Delivery Management','Link deliveries to orders and progress delivery status.','<button class="btn btn-primary" id="add"><i class="fas fa-plus"></i> Add Delivery</button>')+table(['ID','Order','Customer','Address','Status','Actions'],data.map(x=>`<tr data-search="${esc((x.order.customerName+' '+x.deliveryStatus).toLowerCase())}"><td>#${x.id}</td><td>#${x.order.id}</td><td><strong>${esc(x.order.customerName)}</strong></td><td>${esc(x.deliveryAddress)}</td><td>${badge(x.deliveryStatus)}</td><td class="actions"><button class="btn btn-light btn-sm" onclick='editDelivery(${JSON.stringify(x)})'>Edit</button><button class="btn btn-danger btn-sm" onclick="confirmDelete(()=>api.deleteDelivery(${x.id}))">Delete</button></td></tr>`).join(''));document.getElementById('add').onclick=()=>editDelivery(null,orders)},
 users:async()=>{title.textContent='Users';const data=await api.users();content.innerHTML=pageHead('User Management','Review registered customers and administrator roles.')+table(['ID','Name','Email','Role','Actions'],data.map(x=>`<tr data-search="${esc((x.name+' '+x.email+' '+x.role).toLowerCase())}"><td>#${x.id}</td><td><strong>${esc(x.name)}</strong></td><td>${esc(x.email)}</td><td>${badge(x.role)}</td><td class="actions"><button class="btn btn-light btn-sm" onclick='editUser(${JSON.stringify(x)})'>Edit</button>${x.email==='admin@market.lk'?'':`<button class="btn btn-danger btn-sm" onclick="confirmDelete(()=>api.deleteUser(${x.id}))">Delete</button>`}</td></tr>`).join(''))}
};
window.switchView=v=>{currentView=v;document.querySelectorAll('.side-nav a').forEach(a=>a.classList.toggle('active',a.dataset.view===v));views[v]()};
document.querySelectorAll('.side-nav a').forEach(a=>a.onclick=e=>{e.preventDefault();switchView(a.dataset.view)});
document.getElementById('tableSearch').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('tbody tr[data-search]').forEach(r=>r.style.display=r.dataset.search.includes(q)?'':'none')};
window.editCategory=x=>openModal(x?'Edit Category':'Add Category',`<div class="field"><label>Category Name</label><input name="name" value="${esc(x?.name||'')}" required></div>`,fd=>x?api.updateCategory(x.id,{name:fd.get('name')}):api.addCategory({name:fd.get('name')}));
window.editCompany=x=>openModal(x?'Edit Company':'Add Company',`<div class="form-grid"><div class="field full"><label>Company Name</label><input name="name" value="${esc(x?.name||'')}" required></div><div class="field"><label>Email</label><input type="email" name="email" value="${esc(x?.email||'')}"></div><div class="field"><label>Phone</label><input name="phone" value="${esc(x?.phone||'')}"></div><div class="field full"><label>Address</label><textarea name="address">${esc(x?.address||'')}</textarea></div></div>`,fd=>{const b=Object.fromEntries(fd);return x?api.updateCompany(x.id,b):api.addCompany(b)});
window.editProduct=async x=>{const [cats,companies]=await Promise.all([api.categories(),api.companies()]);openModal(x?'Edit Product':'Add Product',`<div class="form-grid"><div class="field full"><label>Product Name</label><input name="name" value="${esc(x?.name||'')}" required></div><div class="field"><label>Category</label><select name="categoryId" required><option value="">Select</option>${options(cats).replace(`value="${x?.category?.id}"`,`value="${x?.category?.id}" selected`)}</select></div><div class="field"><label>Company</label><select name="companyId" required><option value="">Select</option>${options(companies).replace(`value="${x?.company?.id}"`,`value="${x?.company?.id}" selected`)}</select></div><div class="field"><label>Price (LKR)</label><input type="number" step="0.01" min="0.01" name="price" value="${x?.price||''}" required></div><div class="field full"><label>Description</label><textarea name="description">${esc(x?.description||'')}</textarea></div></div>`,fd=>{const b=Object.fromEntries(fd);b.categoryId=Number(b.categoryId);b.companyId=Number(b.companyId);b.price=Number(b.price);return x?api.updateProduct(x.id,b):api.addProduct(b)})};
window.editInventory=async(x,pre)=>{const products=pre||await api.products();openModal(x?'Edit Inventory':'Add Inventory',`<div class="form-grid"><div class="field"><label>Product</label><select name="productId" required><option value="">Select</option>${options(products).replace(`value="${x?.product?.id}"`,`value="${x?.product?.id}" selected`)}</select></div><div class="field"><label>Quantity</label><input type="number" min="0" step="1" name="quantity" value="${x?.quantity??0}" required></div></div><p style="color:#66756e;font-size:.8rem">0 = Out of Stock, 1–5 = Low Stock, above 5 = In Stock.</p>`,fd=>{const b={productId:Number(fd.get('productId')),quantity:Number(fd.get('quantity'))};return x?api.updateInventory(x.id,b):api.addInventory(b)})};
window.editPromotion=async x=>{const products=await api.products();const type=x?.discountType||'PERCENTAGE';const value=x?.discountValue??x?.discountPercentage??'';openModal(x?'Edit Promotion':'Add Promotion',`<div class="form-grid"><div class="field full"><label>Promotion Name</label><input name="name" value="${esc(x?.name||'')}" required></div><div class="field full"><label>Product</label><select name="productId" required><option value="">Select</option>${options(products).replace(`value="${x?.product?.id}"`,`value="${x?.product?.id}" selected`)}</select></div><div class="field"><label>Discount Type</label><select name="discountType"><option value="PERCENTAGE" ${type==='PERCENTAGE'?'selected':''}>Percentage (%)</option><option value="FIXED" ${type==='FIXED'?'selected':''}>Fixed Amount (LKR)</option></select></div><div class="field"><label>Discount Value</label><input type="number" min="0.01" max="999.99" step="0.01" name="discountValue" value="${value}" required></div><div class="field"><label>Status</label><select name="status"><option ${x?.status==='Active'?'selected':''}>Active</option><option ${x?.status==='Inactive'?'selected':''}>Inactive</option></select></div><div class="field"><label>Start Date</label><input type="date" name="startDate" value="${x?.startDate||''}" required></div><div class="field"><label>End Date</label><input type="date" name="endDate" value="${x?.endDate||''}" required></div></div><p style="color:#66756e;font-size:.8rem;margin-top:.6rem">Strategy Pattern: Percentage uses PercentageDiscountStrategy; Fixed Amount uses FixedAmountDiscountStrategy. No database migration is required.</p>`,fd=>{const b=Object.fromEntries(fd);b.productId=Number(b.productId);b.discountValue=Number(b.discountValue);return x?api.updatePromotion(x.id,b):api.addPromotion(b)})};
window.editOrderStatus=x=>openModal(`Order #${x.id} Status`,`<div class="field"><label>Status</label><select name="status"><option ${x.status==='Pending'?'selected':''}>Pending</option><option ${x.status==='Confirmed'?'selected':''}>Confirmed</option><option ${x.status==='Completed'?'selected':''}>Completed</option><option ${x.status==='Cancelled'?'selected':''}>Cancelled</option></select></div>`,fd=>api.updateOrderStatus(x.id,fd.get('status')));
window.viewOrder=async id=>{try{const d=await api.order(id);openModal(`Order #${id}`,`<div style="margin-bottom:1rem"><strong>${esc(d.order.customerName)}</strong> • ${badge(d.order.status)} • ${money(d.order.totalAmount)}</div>${table(['Product','Qty','Unit Price','Subtotal'],d.items.map(i=>`<tr><td>${esc(i.product.name)}</td><td>${i.quantity}</td><td>${money(i.unitPrice)}</td><td><strong>${money(i.subtotal)}</strong></td></tr>`).join(''))}<div style="margin-top:1rem">Delivery: ${d.delivery?badge(d.delivery.deliveryStatus):'<span class="badge muted">Not assigned</span>'}</div>`,async()=>{closeModal()});document.querySelector('#modalForm .modal-actions').style.display='none'}catch(e){notify(e.message,true)}};
window.editDelivery=async(x,pre)=>{const orders=pre||await api.orders();openModal(x?'Edit Delivery':'Add Delivery',`<div class="form-grid"><div class="field full"><label>Order</label><select name="orderId" required><option value="">Select</option>${orders.map(o=>`<option value="${o.id}" ${x?.order?.id===o.id?'selected':''}>#${o.id} • ${esc(o.customerName)} • ${money(o.totalAmount)}</option>`).join('')}</select></div><div class="field full"><label>Delivery Address</label><textarea name="deliveryAddress" required>${esc(x?.deliveryAddress||'')}</textarea></div><div class="field"><label>Status</label><select name="deliveryStatus"><option ${x?.deliveryStatus==='Preparing'?'selected':''}>Preparing</option><option ${x?.deliveryStatus==='Shipped'?'selected':''}>Shipped</option><option ${x?.deliveryStatus==='Delivered'?'selected':''}>Delivered</option></select></div></div>`,fd=>{const b=Object.fromEntries(fd);b.orderId=Number(b.orderId);return x?api.updateDelivery(x.id,b):api.addDelivery(b)})};
window.editUser=x=>openModal('Edit User',`<div class="form-grid"><div class="field"><label>Name</label><input name="name" value="${esc(x.name)}" required></div><div class="field"><label>Role</label><select name="role"><option ${x.role==='CUSTOMER'?'selected':''}>CUSTOMER</option><option ${x.role==='ADMIN'?'selected':''}>ADMIN</option></select></div></div><div class="field"><label>Email (read only)</label><input value="${esc(x.email)}" disabled></div>`,fd=>api.updateUser(x.id,{name:fd.get('name'),role:fd.get('role')}));
switchView('dashboard');
